development:
  adapter: postgresql
  encoding: unicode
  database: bored_fam_development
  pool: 5
  username: bored_fam
  password: ENV["PG_PASSWORD"]
 
test:
  adapter: postgresql
  encoding: unicode
  database: bored_fam_test
  pool: 5
  username: bored_fam
  password: ENV["PG_PASSWORD"]
